const defaults: Record<string, string> = {
  PORT: "3000",
  NODE_ENV: "test",
  ROOT_USERNAME: "root",
  ROOT_EMAIL: "root@example.com",
  ROOT_PASSWORD: "root",
  MYSQL_HOST: "127.0.0.1",
  MYSQL_PORT: "3306",
  MYSQL_DATABASE: "wildfire_test",
  MYSQL_USER: "wildfire",
  MYSQL_PASSWORD: "wildfire",
  MINIO_ROOT_USER: "minioadmin",
  MINIO_ROOT_PASSWORD: "minioadmin",
  MINIO_ENDPOINT: "localhost",
  MINIO_PORT: "9000",
  MINIO_USE_SSL: "false",
  MINIO_BUCKET: "content",
  MINIO_REGION: "us-east-1",
  MINIO_REQUEST_TIMEOUT_MS: "15000",
  CONTENT_MAX_UPLOAD_BYTES: "104857600",
  HTSHADOW_PATH: "/tmp/htshadow",
  JWT_SECRET: "test-secret",
  JWT_ISSUER: "wildfire",
  AUTH_SESSION_COOKIE_NAME: "wildfire_session_token",
  AUTH_LOGIN_RATE_LIMIT_MAX_ATTEMPTS: "10",
  AUTH_LOGIN_RATE_LIMIT_WINDOW_SECONDS: "60",
  AUTH_LOGIN_LOCKOUT_THRESHOLD: "5",
  AUTH_LOGIN_LOCKOUT_SECONDS: "300",
  DISPLAY_RUNTIME_RATE_LIMIT_WINDOW_SECONDS: "60",
  DISPLAY_RUNTIME_AUTH_CHALLENGE_MAX_ATTEMPTS: "60",
  DISPLAY_RUNTIME_AUTH_VERIFY_MAX_ATTEMPTS: "60",
  INVITE_TOKEN_TTL_SECONDS: "86400",
  INVITE_ACCEPT_BASE_URL: "http://localhost:3000/accept-invite",
  RESET_PASSWORD_BASE_URL: "http://localhost:3000/reset-password",
  EMAIL_CHANGE_TOKEN_TTL_SECONDS: "86400",
  EMAIL_CHANGE_VERIFY_BASE_URL: "http://localhost:3000/verify-email-change",
  LOG_LEVEL: "info",
  LOG_PRETTY: "false",
  AUDIT_QUEUE_ENABLED: "true",
  AUDIT_QUEUE_CAPACITY: "5000",
  AUDIT_EXPORT_MAX_ROWS: "100000",
  SCHEDULE_TIMEZONE: "UTC",
  CORS_ORIGINS: "http://localhost:3000",
};

for (const [key, value] of Object.entries(defaults)) {
  if (process.env[key] === undefined || process.env[key] === "") {
    process.env[key] = value;
  }
}
